name: Update Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.name "HassanAbbas10"
          git config --local user.email "hassanabbas05674@gmail.com"

      - name: Update snake animation
        run: |
          git add -A
          git commit -m "Update snake animation" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
